trigger:
- main

stages:
# Stage: Build
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: Build
    displayName: "Build Job"
    pool:
      vmImage: 'ubuntu-latest'
    steps: 
    # Step 1: List contents in default working directory
    - bash: |
        echo "Contents in System Default Working Directory"
        ls -R $(System.DefaultWorkingDirectory)

    # Step 2: List contents in artifact staging directory before copy
    - bash: |
        echo "Before copying, contents in Build Artifact Directory"
        ls -R $(Build.ArtifactStagingDirectory)

    # Step 3: Copy files to artifact staging directory
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)/terraform-manifests'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        OverWrite: true

    # Step 4: List files after copy
    - bash: |
        echo "After copying to Build Artifact Directory"
        ls -R $(Build.ArtifactStagingDirectory)

    # Step 5: Publish build artifacts
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'terraform-manifests'
        publishLocation: 'Container'
